"use client"

import { useEffect, useMemo, useState } from "react"
import { useRouter } from "next/navigation"
import { supabase } from "../../lib/supabase/client"

export default function GeneratePage() {
  const router = useRouter()

  const [status, setStatus] = useState("Authenticating...")
  const [plan, setPlan] = useState("")
  const [loading, setLoading] = useState(true)

  const preview = useMemo(() => {
    if (!plan) return ""
    return plan
  }, [plan])

  useEffect(() => {
    const generatePlan = async () => {
      try {
        const {
          data: { user },
          error: authError,
        } = await supabase.auth.getUser()

        if (authError || !user) {
          router.push("/login")
          return
        }

        setStatus("Generating your personalized plan...")

        const res = await fetch("/api/generate-plan", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ userId: user.id }),
        })

        if (!res.ok) {
          const errorData = await res
            .json()
            .catch(() => ({ error: "Server returned an error" }))
          throw new Error(errorData.error || "Generation failed")
        }

        const data = await res.json()

        if (!data.plan) {
          throw new Error("No plan was generated by the AI.")
        }

        const planText = JSON.stringify(data.plan, null, 2)

        localStorage.setItem("plan", planText)
        setPlan(planText)
        setStatus("Your plan is ready!")
      } catch (err: any) {
        console.error("GENERATION PAGE ERROR:", err)
        alert(err.message || "Something went wrong. Please try again.")
        router.push("/onboarding")
      } finally {
        setLoading(false)
      }
    }

    generatePlan()
  }, [router])

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-white px-4">
        <div className="text-center max-w-sm">
          <div className="w-16 h-16 border-4 border-purple-500 border-t-transparent rounded-full animate-spin mx-auto mb-6" />
          <h1 className="text-2xl font-bold text-slate-900 mb-2">
            Generating Your Plan
          </h1>
          <p className="text-slate-500">{status}</p>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-white px-4 py-10">
      <div className="max-w-3xl mx-auto">
        <h1 className="text-3xl font-bold text-slate-900 mb-6 text-center">
          Your AI Fitness Plan
        </h1>

        <div className="bg-white border border-gray-200 rounded-3xl p-6 shadow-sm">
          <pre className="whitespace-pre-wrap text-sm text-slate-700 leading-relaxed">
            {preview || "No plan available."}
          </pre>
        </div>

        <div className="flex justify-center mt-8">
          <button
            onClick={() => router.push("/dashboard/home")}
            className="px-6 py-3 rounded-xl bg-gradient-to-r from-purple-600 to-cyan-500 text-white font-semibold"
          >
            Confirm Plan
          </button>
        </div>
      </div>
    </div>
  )
}